keywords:
  security:
    - 'access control'
    - 'access role'
    - 'adware'
    - 'adversarial'
    - 'malware'
    - 'spyware'
    - 'ransom-ware'
    - 'aes'
    - 'antivirus'
    - 'asset'
    - 'audit'
    - 'authority'
    - 'authorise'
    - 'availability'
    - 'bitlocker'
    - 'biometric'
    - 'blacklist'
    - 'botnet'
    - 'buffer overflow'
    - 'burp'
    - 'ctf'
    - 'capture the flag'
    - 'cbc'
    - 'certificate'
    - 'checksum'
    - 'cipher'
    - 'clearance'
    - 'confidential'
    - 'clickfraud'
    - 'clickjacking'
    - 'cloudflare'
    - 'cookie'
    - 'crc'
    - 'credential'
    - 'crypt'
    - 'csrf'
    - 'ddos'
    - 'danger'
    - 'data exfiltrate'
    - 'data exfiltration'
    - 'data breach'
    - 'decode'
    - 'defence'
    - 'defense'
    - 'defensive programming'
    - 'delegation'
    - 'denial of service'
    - 'diffie hellman'
    - 'directory traversal'
    - 'disclose'
    - 'disclosure'
    - 'dmz'
    - 'dotfuscator'
    - 'dsa'
    - 'ecdsa'
    - 'encode'
    - 'encrypt'
    - 'escrow'
    - 'exploit'
    - 'evil twin'
    - 'fingerprint'
    - 'firewall'
    - 'forge'
    - 'forgery'
    - 'fuzz'
    - 'fraud'
    - 'gnupg'
    - 'gss api'
    - 'hack'
    - 'hash'
    - 'hijacking'
    - 'hmac'
    - 'honeypot'
    - 'honey pot'
    - 'hsm'
    - 'inject'
    - 'insecure'
    - 'integrity'
    - 'intrusion'
    - 'intruder'
    - 'ipsec'
    - 'kerberos'
    - 'ldap'
    - 'login'
    - 'metasploit'
    - 'meterpreter'
    - 'malicious'
    - 'md5'
    - 'nessus'
    - 'nonce'
    - 'nss'
    - 'oauth'
    - 'obfuscate'
    - 'openssl'
    - 'openssh'
    - 'openvas'
    - 'open auth'
    - 'open redirect'
    - 'openid'
    - 'owasp'
    - 'password'
    - 'pbkdf2'
    - 'pci dss'
    - 'pgp'
    - 'phishing'
    - 'pki'
    - 'privacy'
    - 'private key'
    - 'privilege'
    - 'privilege escalation'
    - 'permission escalation'
    - 'public key'
    - 'peidss'
    - 'pen test'
    - 'penetration test'
    - 'protect'
    - 'rainbow table'
    - 'rbac'
    - 'rc4'
    - 'repudiation'
    - 'rfc 2898'
    - 'rijndael'
    - 'rootkit'
    - 'rsa'
    - 'safe'
    - 'salt'
    - 'saml'
    - 'sanitise'
    - 'sandbox'
    - 'scam'
    - 'scriptkiddie'
    - 'scripting'
    - 'secur'
    - 'sftp'
    - 'sha'
    - 'shell code'
    - 'shib boleth'
    - 'signature'
    - 'signed'
    - 'signing'
    - 'single sign on'
    - 'smart assembly'
    - 'smartassembly'
    - 'snif'
    - 'spam'
    - 'spnego'
    - 'spoof'
    - 'ssh'
    - 'ssl'
    - 'sso'
    - 'steganography'
    - 'tampering'
    - 'theft'
    - 'threat'
    - 'tls'
    - 'transport'
    - 'tunneling'
    - 'tunnelling'
    - 'trojan'
    - 'trust'
    - 'two factor'
    - 'user account'
    - 'user name'
    - 'violate'
    - 'validate'
    - 'virus'
    - 'white list'
    - 'worm'
    - 'x 509'
    - 'X.509'
    - 'xss'
    - 'xxe'
    - 'ssrf'
    - 'zero day'
    - '0 day'
    - 'zombie computer'
    - 'attack'
    - 'vulnerability'
    - 'attack vector'
    - 'authentication'
    - 'cross site'
    - 'sensitiveinformation'
    - 'leak'
    - 'information exposure'
    - 'path traversal'
    - 'use after free'
    - 'double free'
    - 'man in the middle'
    - 'man in middle'
    - 'mitm'
    - 'poisoning'
    - 'unauthorise'
    - 'dot dot slash'
    - 'bypass'
    - 'session fixation'
    - 'forced browsing'
    - 'nvd'
    - 'cwe'
    - 'cve'
    - 'capec'
    - 'cpe'
    - 'common weakness enumeration'
    - 'common platform enumeration'
    - 'crack'
    - 'xml entity expansion'
    - 'http parameter pollution'
    - 'eavesdropping'
    - 'cryptanalysis'
    - 'http flood'
    - 'xml flood'
    - 'udp flood'
    - 'top flood'
    - 'top syn flood'
    - 'steal'
    - 'ssl flood'
    - 'j2ee misconfigu-ration'
    - 'asp.net misconfiguration'
    - 'improper neutralisation'
    - 'race condition'
    - 'null pointer dereference'
    - 'untrusted pointerdereference'
    - 'trap door'
    - 'back door'
    - 'time bomb'
    - 'xml bomb'
    - 'logic bomb'
    - 'captcha'
    - 'deadlock'
    - 'missing synchronisation'
    - 'incorrect synchronisation'
    - 'improper synchronisation'
    - 'illegitimate'
    - 'breach'
    - 'sql injection'