### SecurityAware Configuration Settings
---

securityaware:

### Toggle application level debug (does not toggle framework debugging)
  debug: true

### Where external (third-party) plugins are loaded from
  plugin_dir: ~/.securityaware/plugins/

### Where all plugin configurations are loaded from
# plugin_config_dir: /etc/securityaware/plugins.d/

### Where external templates are loaded from
# template_dir: /var/lib/securityaware/templates/

### The log handler label
  log_handler: colorlog

### The output handler label
  output_handler: jinja2

### Threading
  local_threads: 8


log.colorlog:

### Where the log file lives (no log file by default)
# file: null

### The level for which to log.  One of: info, warning, error, fatal, debug
  level: info

### Whether or not to log to console
  to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
  rotate: true

### Max size in bytes that a log file can grow until it is rotated.
  max_bytes: 512000

### The maximun number of log files to maintain when rotating
  max_files: 4

plugins.github_collector:
  enabled: true

plugins.compare:
  enabled: true

plugins.filter:
  enabled: true

plugins.codeql_extract_labels:
  enabled: true

plugins.function_boundary:
  enabled: true

plugins.match_location:
  enabled: true

plugins.labeler:
  enabled: true

plugins.plot_matrix:
  enabled: true

plugins.filter_frame:
  enabled: true

plugins.file_collector:
  enabled: true

plugins.find_references:
  enabled: true

plugins.sampling:
  enabled: true

plugins.histogram:
  enabled: true

plugins.preprocess:
  enabled: true

plugins.code2vec:
  enabled: true

plugins.filter_fn_size:
  enabled: true

plugins.match_path_contexts:
  enabled: true