### SecurityAware Configuration Settings
---

securityaware:

### Toggle application level debug (does not toggle framework debugging)
  debug: true

### Where external (third-party) plugins are loaded from
  plugin_dir: /var/lib/securityaware/plugins/

### Where all plugin configurations are loaded from
# plugin_config_dir: /etc/securityaware/plugins.d/

### Where external templates are loaded from
# template_dir: /var/lib/securityaware/templates/

### Where external transforms for jscodeshift are loaded from
  transforms_dir: /etc/securityaware/transforms/

### The log handler label
  log_handler: colorlog

### The output handler label
  output_handler: jinja2

### Project extensions:
  proj_ext:
    - ".js"

### Threading
  local_threads: 8


log.colorlog:

### Where the log file lives (no log file by default)
# file: null

### The level for which to log.  One of: info, warning, error, fatal, debug
 level: info

### Whether or not to log to console
 to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
# rotate: false

### Max size in bytes that a log file can grow until it is rotated.
# max_bytes: 512000

### The maximun number of log files to maintain when rotating
# max_files: 4


plugin.github_collector:
  enabled: true

plugin.compare:
  enabled: true

plugin.filter:
  enabled: true

plugin.codeql_extract_labels:
  enabled: true

plugin.function_boundary:
  enabled: true

plugin.match_location:
  enabled: true

plugin.labeler:
  enabled: true

plugin.plot_matrix:
  enabled: true
